name: klaptrap
favicon: null
layout_spectrum: 0.1435
typography_spectrum: 0.33664
title: 'A life in digital, closing the loop'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-43017399-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4285f4'
    - '#ea4335'
    - '#fbbc05'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.6875
  lightness: 0.48006158138368693
  saturation: 0.5997873743406462
  rhythmicContrast: 0.11008770510733812
purpose:
  - name: null
    item: null
    url: null
